name: Continious Integration

on:
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm i
      - name: Lint Validations
        run:  npm run lint
      - name: Build with Next.js
        run:  npm run build
